import type {
  User,
  LandlordProfile,
  StudentProfile,
  Property,
  Review,
  HomeMatchEvent,
} from '@/lib/types';
import type { RoommateProfile } from '@/ai/flows/roommate-matching';
import { PlaceHolderImages } from '@/lib/placeholder-images';

const getImage = (id: string) => PlaceHolderImages.find(img => img.id === id)?.imageUrl || '';

export const users: User[] = [
  { id: 'user-1', role: 'student', name: 'Elena Garcia', avatarUrl: getImage('avatar2'), isVerified: true },
  { id: 'user-2', role: 'student', name: 'Luca Rossi', avatarUrl: getImage('avatar1'), isVerified: true },
  { id: 'user-3', role: 'landlord', name: 'Javier Fernandez', avatarUrl: getImage('avatar3'), isVerified: true },
  { id: 'user-4', role: 'student', name: 'Sophie Müller', avatarUrl: getImage('avatar4'), isVerified: false },
  { id: 'user-5', role: 'student', name: 'Liam Byrne', avatarUrl: getImage('avatar5'), isVerified: true },
  { id: 'user-6', role: 'student', name: 'Chloé Dubois', avatarUrl: getImage('avatar6'), isVerified: true },
];

export const properties: Property[] = [
  {
    id: 'prop-1',
    landlordId: 'user-3',
    title: 'Habitación luminosa en Gràcia',
    description: 'Habitación en piso recién reformado con mucha luz natural. Ideal para estudiantes que buscan un ambiente tranquilo.',
    city: 'Barcelona',
    neighborhood: 'Gràcia',
    addressApprox: 'Cerca de la Plaça del Sol',
    coords: { lat: 41.4036, lng: 2.154 },
    pricePerMonth: 620,
    expensesIncluded: true,
    bedrooms: 3,
    bathrooms: 2,
    squareMeters: 110,
    room_sqm: 12,
    photos: [getImage('property1-room'), getImage('property1-living'), getImage('property1-kitchen')],
    amenities: ['Wifi', 'Aire Acondicionado', 'Lavadora', 'Cocina equipada'],
    rules: ['No fumar', 'No se admiten mascotas', 'No fiestas'],
    availability: [new Date()],
    rating: 4.8,
    reviewsCount: 12,
    type: 'private_room',
  },
  {
    id: 'prop-2',
    landlordId: 'user-3',
    title: 'Acogedora habitación en Malasaña',
    description: 'Habitación individual en un piso compartido en el corazón de Madrid. Perfecta para vivir la vida de la ciudad.',
    city: 'Madrid',
    neighborhood: 'Malasaña',
    addressApprox: 'Junto a la Plaza del Dos de Mayo',
    coords: { lat: 40.4255, lng: -3.7046 },
    pricePerMonth: 580,
    expensesIncluded: true,
    bedrooms: 4,
    bathrooms: 1,
    squareMeters: 100,
    room_sqm: 10,
    photos: [getImage('property2-room'), getImage('property2-living')],
    amenities: ['Wifi', 'Calefacción', 'Ascensor'],
    rules: ['No fumar'],
    availability: [new Date()],
    rating: 4.5,
    reviewsCount: 8,
    type: 'private_room',
  },
  {
    id: 'prop-3',
    landlordId: 'user-3',
    title: 'Habitación en piso compartido en Russafa',
    description: 'Amplia habitación con balcón, ideal para estudiantes de la UPV. El piso tiene un gran ambiente internacional.',
    city: 'Valencia',
    neighborhood: 'Russafa',
    addressApprox: 'Cerca del Mercat de Russafa',
    coords: { lat: 39.4633, lng: -0.3733 },
    pricePerMonth: 450,
    expensesIncluded: false,
    bedrooms: 3,
    bathrooms: 2,
    squareMeters: 120,
    room_sqm: 15,
    photos: [getImage('property3-room'), getImage('property3-living'), getImage('property3-kitchen')],
    amenities: ['Wifi', 'Balcón', 'Lavadora'],
    rules: ['Se admiten mascotas pequeñas'],
    availability: [new Date()],
    rating: 4.7,
    reviewsCount: 15,
    type: 'private_room',
  },
  {
    id: 'prop-4',
    landlordId: 'user-3',
    title: 'Habitación económica en Triana',
    description: 'Habitación funcional y a buen precio, perfecta para un estudiante, cerca del río y de la universidad.',
    city: 'Sevilla',
    neighborhood: 'Triana',
    addressApprox: 'Cerca del Puente de Triana',
    coords: { lat: 37.3826, lng: -6.0065 },
    pricePerMonth: 380,
    expensesIncluded: true,
    bedrooms: 5,
    bathrooms: 2,
    squareMeters: 130,
    room_sqm: 9,
    photos: [getImage('property4-room')],
    amenities: ['Wifi', 'Aire Acondicionado'],
    rules: ['No fumar'],
    availability: [new Date()],
    rating: 4.9,
    reviewsCount: 5,
    type: 'private_room',
  },
];

export const reviews: Review[] = [
    { id: 'rev-1', author: users[1], rating: 5, comment: '¡El piso es genial y Javier es un anfitrión increíble! Muy recomendable.', date: 'hace 2 semanas', reviewFor: { type: 'property', id: 'prop-1' } },
    { id: 'rev-2', author: users[3], rating: 4, comment: 'Una estancia muy agradable. La ubicación es perfecta.', date: 'hace 1 mes', reviewFor: { type: 'property', id: 'prop-2' } },
    { id: 'rev-3', author: users[0], rating: 5, comment: 'Javier ha sido el mejor propietario que he tenido. Siempre atento y dispuesto a ayudar en todo. ¡Un 10!', date: 'hace 3 semanas', reviewFor: { type: 'user', id: 'user-3' } },
    { id: 'rev-4', author: users[1], rating: 5, comment: 'Elena es una compañera de piso fantástica. Muy limpia, respetuosa y siempre con una sonrisa.', date: 'hace 1 mes', reviewFor: { type: 'user', id: 'user-1' } },
    { id: 'rev-5', author: users[4], rating: 4, comment: 'Javier fue muy rápido solucionando un problema con la calefacción. Se agradece su eficiencia.', date: 'hace 2 meses', reviewFor: { type: 'user', id: 'user-3' } },
];

export const events: HomeMatchEvent[] = [
    { id: 'event-1', title: 'Noche de Tapas en Gràcia', type: 'Cena', description: 'Vamos a explorar los mejores bares de tapas del barrio.', date: '25 de Julio, 2024', location: 'Gràcia, Barcelona', coverImage: getImage('event1'), attendeesCount: 8, hostedBy: users[0] },
    { id: 'event-2', title: 'Tour a pie por el Madrid de los Austrias', type: 'Tour', description: 'Descubre la historia oculta en el centro de Madrid.', date: '28 de Julio, 2024', location: 'Centro, Madrid', coverImage: getImage('event2'), attendeesCount: 15, hostedBy: users[1] },
    { id: 'event-3', title: 'Grupo de estudio en Valencia', type: 'Estudio', description: 'Quedada para preparar los finales en una cafetería chula.', date: '30 de Julio, 2024', location: 'Russafa, Valencia', coverImage: getImage('event3'), attendeesCount: 6, hostedBy: users[2] }
];

export const studentProfilesForMatching: RoommateProfile[] = [
    {
        userId: 'user-1',
        age: 22,
        occupation: 'Estudiante de Master en IA',
        budgetMin: 500,
        budgetMax: 650,
        arrivalDate: '2024-09-01',
        departureDate: '2025-06-30',
        cleanlinessPreference: 'clean',
        noisePreference: 'quiet',
        petsPreference: false,
        smokingPreference: false,
        visitorPreference: 'occasional',
        sleepingHabits: 'night owl',
        interests: ['inteligencia artificial', 'senderismo', 'fotografía', 'cine'],
        matchVisibility: true,
    },
    {
        userId: 'user-2',
        age: 24,
        occupation: 'Estudiante de Erasmus de Arquitectura',
        budgetMin: 450,
        budgetMax: 600,
        arrivalDate: '2024-09-15',
        departureDate: '2025-01-31',
        cleanlinessPreference: 'neutral',
        noisePreference: 'neutral',
        petsPreference: true,
        smokingPreference: false,
        visitorPreference: 'frequent',
        sleepingHabits: 'flexible',
        interests: ['diseño', 'música en vivo', 'viajar', 'cocina italiana'],
        matchVisibility: true,
    },
    {
        userId: 'user-4',
        age: 21,
        occupation: 'Estudiante de Diseño Gráfico',
        budgetMin: 500,
        budgetMax: 700,
        arrivalDate: '2024-09-01',
        departureDate: '2025-07-15',
        cleanlinessPreference: 'very clean',
        noisePreference: 'very quiet',
        petsPreference: false,
        smokingPreference: false,
        visitorPreference: 'rare',
        sleepingHabits: 'early bird',
        interests: ['arte', 'yoga', 'lectura', 'museos'],
        matchVisibility: true,
    },
    {
        userId: 'user-5',
        age: 25,
        occupation: 'Programador Junior',
        budgetMin: 600,
        budgetMax: 800,
        arrivalDate: '2024-08-15',
        departureDate: '2025-08-14',
        cleanlinessPreference: 'clean',
        noisePreference: 'quiet',
        petsPreference: false,
        smokingPreference: true,
        visitorPreference: 'occasional',
        sleepingHabits: 'night owl',
        interests: ['videojuegos', 'programación', 'series', 'cerveza artesanal'],
        matchVisibility: true,
    },
    {
        userId: 'user-6',
        age: 23,
        occupation: 'Estudiante de Doctorado en Biología',
        budgetMin: 400,
        budgetMax: 550,
        arrivalDate: '2024-10-01',
        departureDate: '2025-09-30',
        cleanlinessPreference: 'neutral',
        noisePreference: 'quiet',
        petsPreference: true,
        smokingPreference: false,
        visitorPreference: 'rare',
        sleepingHabits: 'early bird',
        interests: ['naturaleza', 'animales', 'documentales', 'correr'],
        matchVisibility: true,
    },
];
